---
  title: "Advanced Course: Introduction to R"
  author: "A. Kaliontzopoulou, A. Jesús Muñoz-Pajares, P. Tarroso, U. Enriquez-Urzelai"
  date: "4-8 November 2019"

---
  
R is a programming language for statistical computing freely available, and with excellent graphical capabilities. As such, it has become an indispensable tool in all fields of biological research: many new statistical methods have been developed in recent years using R and numerous top-rank journals nowadays favor its use for the publication of scientific results.

The objective of this short course is to provide a general introduction towards using R for data analyses. We will provide a general review of basic operations, data types and management, aiming at familiarizing the students with the R environment without requirement of prior experience in R or programming. The course will follow a hands-on approach, with a theoretical background previous to each practical session. Participants are encouraged to bring their own data.

This course will provide the basis for more advanced courses on specific topics using R, and it will be a requirement for students interested in enrolling in those courses.

